#!/usr/bin/env bash
# install nginx

sudo apt update -y
sudo apt install -y nginx

# listen on port 80
sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World!" > /var/www/html/index.html

#backup website config
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default.backup

# replace redirection
new_string="    location /redirect_me {
    return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
}"
sudo sed -i '53r /dev/stdin' /etc/nginx/sites-enabled/default <<< "$new_string"

#Start nginx
sudo service nginx restart
