#!/usr/bin/env bash
# create a smylink of the default available site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill $(pgrep nginx)
