#!/usr/bin/env bash
# print ls

file="/etc/passwd"

if [ -f "$file" ];
then
    while IFS=':' read -r username password userid groupid user_info homedir shell; do
        echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell. User $userid's place is protected by the passcode $password, more info about the user here: $user_info"
    done < "$file"
else
    echo "File does not exist: $file"
fi
