#!/usr/bin/env bash
# print ls

file="school"
if test -e $file;
then
    echo "$file file exists"

    content=""
    cat $file > content
    if test -s "$content"
    then
	echo "$file file not is empty"
    else
	echo "$file file is empty"
    fi

    if test -f "$file"
    then
	echo "school is a regular file"
    fi
else
    echo "$file file does not exist"
fi
